### ISSUE TITLE
✨[Feat] Frontend 스타일 수정

### ISSUE THREAD

**Issue by guswns7452** [guswns7452/Perst#33]
## ✨ 어떤 기능인가요?
프론트엔드 세부적인 디자인 수정 필요성 대두됨
<br>

## ✅ 작업 상세 내용
> 수정 할 때마다 추가할 예정임
- [x] Google Font 반영
- [x] 로그인 페이지 수정
  - 아이콘 별로라 삭제
  - 전화번호 입력 필드는 숫자만 입력 가능하도록 수정
- [x] Intro 페이지 여러 사진 추가하기
  - PageView 자동 넘어감
  - PageView만 존재하면 심심하여 인디케이터 추가 
- [x] 스타일 둘러보기 선택 완료 버튼 모든 TabBar에서 표시되도록 수정
  -  기존의 색상 탭에서만 표시되던 버튼을 하나로 통합
- [x]  perst 로고 archivoBlack 폰트로 통일
- [x] 스타일 분석하기 탭 설명 추가 
  - Scrollview로 구성
  - 추후 더 넣을 내용 논의하여 추가하기
<br>

### 1️⃣ 로그인 페이지 수정
| 기존 | 수정 |
| :--: | :--: |
|![image](https://github.com/guswns7452/Perst/assets/31847789/0d45c803-6b9b-48d3-802b-577758018f07)| ![image](https://github.com/guswns7452/Perst/assets/31847789/9233b80a-cf60-41b8-93aa-ab9cb372e839)|

### 2️⃣  Intro 페이지 여러 사진 추가하기
| 기존 | 수정 |
| :--: | :--: |
|![image](https://github.com/guswns7452/Perst/assets/31847789/e9a78d41-854b-41fc-92f7-35b0d6630d80)|![image](https://github.com/guswns7452/Perst/assets/31847789/a7a44950-86bf-4917-83c5-db275b854e87)|

### 3️⃣ 선택 완료 버튼 모든 TabBar에서 표시되도록 수정
| 기존 | 수정 |
| :--: | :--: |
|![image](https://github.com/guswns7452/Perst/assets/31847789/4e70b042-669a-4b85-a435-b890de25c912)|![image](https://github.com/guswns7452/Perst/assets/31847789/e0437a40-624d-4402-a86a-fad543e2240d)|

### 4️⃣ 스타일 분석하기 탭 설명 추가
| 기존 | 수정 |
| :--: | :--: |
|![image](https://github.com/guswns7452/Perst/assets/31847789/9557e338-fb96-48cd-99a8-169755bf4ae9)|![image](https://github.com/guswns7452/Perst/assets/31847789/e44ff0d7-be0a-4aa7-aa99-971c514b2b92)|

### 5️⃣ 로고 폰트 통일
![image](https://github.com/guswns7452/Perst/assets/31847789/766fcb00-c79e-4fc2-88b1-2333229dc093)

**Comment by dahyun-da** [comment]
merge 할 시 conflict 생각할 부분

Login 페이지 -> promise.then을 사용하여 token 값이 생성될 시 tabbar 페이지로 넘어가기
StyleTour 페이지 -> 로그인 된 성별에 따라서 검색 default 값 수정, 스타일 default 값 스포티로 수정, 색상을 이용한 검색 가능, 남성 스타일 분석 오류 해결
